Repository jenkinsci/flyway-api-plugin, pull requests merged in 2024-08, with the labels that each got.

#90 Update Jenkins Security Scan action
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#93 Refresh test data
  src/test/java/io/jenkins/plugins/flyway/MariaDbSmokeTest.java
  src/test/java/io/jenkins/plugins/flyway/MySqlDbSmokeTest.java
  src/test/java/io/jenkins/plugins/flyway/PostgresSmokeTest.java
Labels: tests

#94 Automated PR
  pom.xml
Labels: dependencies
